DEV: Convert to native class syntax
discourse/discourse-insert-video pull request #53
Opened 2024-11-29 10:43 UTC by davidtaylorhq

2024-11-29 10:55 UTC, CvX requested changes

2024-11-29 10:55 UTC, CvX commented on javascripts/discourse/components/custom-simple-list.js
> +    return this.placeholderKey || themePrefix("simple_list_placeholder");
Hehe (recursion goes brrrr 😄)

2024-11-29 10:58 UTC, davidtaylorhq commented on javascripts/discourse/components/custom-simple-list.js
> +    return this.placeholderKey || themePrefix("simple_list_placeholder");
😬 I wonder how this worked before!

2024-11-29 14:57 UTC, davidtaylorhq commented on javascripts/discourse/components/custom-simple-list.js
> +    return this.placeholderKey || themePrefix("simple_list_placeholder");
updated

2024-12-02 13:29 UTC, CvX approved these changes

2024-12-02 13:29 UTC, merged